version: "3.4"

services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./docker-data/mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - tdrive_network

  node:
    image: tdrive/tdrive-node
    container_name: node
    ports:
      - 4000:3000
      - 8000:3000
      - 9229:9229
    environment:
      - DEV=dev
      - SEARCH_DRIVER=mongodb
      - DB_DRIVER=mongodb
      - PUBSUB_TYPE=local
      - STATIC_ROOT=/frontend
    build:
      context: .
      dockerfile: docker/tdrive-node/Dockerfile
      target: development
    volumes:
      - ./backend/node:/usr/src/app
      - ./frontend/dist:/frontend
      - ./docker-data/documents/:/storage/
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - tdrive_network

networks:
  tdrive_network:
    driver: bridge
         
