name: docker-build

on:
  pull_request:
    branches: [main]
    paths:
      - "twake/docker/**"

jobs:
  build-nginx:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: cd twake && docker build -t twaketech/tdrive-nginx -f docker/twake-nginx/Dockerfile .

  build-node:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: cd twake && docker build --target production -t docker-registry.linagora.com/tdrive/tdrive-node -f docker/twake-node/Dockerfile .
